#Swerve Motors
FRONT_LEFT_DRIVE = 12
FRONT_RIGHT_DRIVE = 11
BACK_LEFT_DRIVE = 14
BACK_RIGHT_DRIVE = 13

FRONT_LEFT_TURN = 22
FRONT_RIGHT_TURN = 21
BACK_LEFT_TURN = 24
BACK_RIGHT_TURN = 23

#Intake Motors
INTAKE_TILT_MOTOR = 41
INTAKE_ROLLER_MOTOR = 42

#Amp Motors
AMP_LIFT_MOTOR = 51
AMP_ROLLER_MOTOR = 52

#Shooter Motors
SHOOTER_MOTOR_L = 61
SHOOTER_MOTOR_R = 62
SHOOTER_FEEDER_MOTOR = 63
SHOOTER_TILT_MOTOR_L = 64
SHOOTER_TILT_MOTOR_R = 65

#Climber Motors
CLIMBER_MOTOR_L = 71
CLIMBER_MOTOR_R = 72

#Cancoders
FRONT_LEFT_DRIVE_ENCODER = 32
FRONT_RIGHT_DRIVE_ENCODER = 31
BACK_LEFT_DRIVE_ENCODER = 34
BACK_RIGHT_DRIVE_ENCODER = 33

SHOOTER_TILT_ENCODER = 35

#Gyro
PIGEON = 41

#Limit Switches DIO
INTAKE_TILT_TOP_LIMIT_SWITCH = 0
INTAKE_TILT_BOTTOM_LIMIT_SWITCH = 1
SHOOTER_TILT_TOP_LIMIT_SWITCH = 2
SHOOTER_TILT_BOTTOM_LIMIT_SWITCH = 3
AMP_LIFT_BOTTOM_LIMIT_SWITCH = 4

#Photoeyes DIO
INTAKE_PHOTOEYE = 5
INTAKE_HOLDER_PHOTOEYE = 6
AMP_HOLDER_PHOTOEYE = 7
SHOOTER_PHOTOEYE = 8