#Swerve Motors
FRONT_LEFT_DRIVE = 12
FRONT_RIGHT_DRIVE = 11
BACK_LEFT_DRIVE = 14
BACK_RIGHT_DRIVE = 13

FRONT_LEFT_TURN = 22
FRONT_RIGHT_TURN = 21
BACK_LEFT_TURN = 24
BACK_RIGHT_TURN = 23

#Intake Motors
INTAKE_TILT = 0
ROLLER_MOTOR = 1

#Amp Motors
LIFT_MOTOR = 0
ROLLER_MOTOR = 1

#Shooter Motors
SHOOTER_MOTOR_L = 0
SHOOTER_MOTOR_R = 1

FEEDER_MOTOR = 2

TILT_MOTOR_L = 3
TILT_MOTOR_R = 4

#Climber Motors
LEFT_CLIMBER = 0
RIGHT_CLIMBER = 1

#Cancoders
FRONT_LEFT_DRIVE_ENCODER = 32
FRONT_RIGHT_DRIVE_ENCODER = 31
BACK_LEFT_DRIVE_ENCODER = 34
BACK_RIGHT_DRIVE_ENCODER = 33

SHOOTER_CANCODER = 41

#Limit Switches DIO
INTAKE_TILT_TOP_LIMIT_SWITCH = 0
INTAKE_TILT_BOTTOM_LIMIT_SWITCH = 1

SHOOTER_TILT_TOP_LIMIT_SWITCH = 2
SHOOTER_TILT_BOTTOM_LIMIT_SWITCH = 3

AMP_LIFT_BOTTOM_LIMIT_SWITCH = 4

#Photoeyes DIO
INTAKE_PHOTOEYE = 0
INTAKE_HOLDER_PHOTOEYE = 1
AMP_HOLDER_PHOTOEYE = 2
SHOOTER_PHOTOEYE = 3